Repository halo-dev/test-infra, pull requests merged in 2022-03, with the labels that each got.

#4 Add retitle plugin
  config/prow/plugins.yaml
Labels: lgtm

#7 Set the default merge strategy for halo-dev organization
  config/prow/config.yaml
Labels: kind/feature, lgtm, approved, sig/test-infra

#6 Add additional labels for other merge methods
  config/prow/plugins.yaml
Labels: kind/feature, lgtm, approved

#8 chore: add lifecycle plugins for halo-dev org.
  config/prow/plugins.yaml
Labels: lgtm, approved

#9 chore: add milestone plugin
  config/prow/plugins.yaml
Labels: lgtm, approved

#10 Add metersphere support
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: kind/feature, lgtm, approved
