Repository halo-dev/test-infra, pull requests merged in 2022-05, with the labels that each got.

#21 Add release-note plugin for halo-dev organization
  config/prow/plugins.yaml
Labels: lgtm, approved

#22 feat: add improvement label
  config/prow/labels.yaml
Labels: release-note-none, lgtm, approved

#23 Add postsubmits and periodics jobs to redeploy Prow and sync labels
  config/jobs/halo-dev/test-infra/test-infra-trusted.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/plugins.yaml
Labels: kind/feature, release-note-none, lgtm, approved

#24 Update Prow to v20220518-4571841471
  config/prow/cluster/cherrypicker_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/needs-rebase_deployment.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
Labels: release-note-none, lgtm, approved
