Repository halo-dev/test-infra, pull requests merged in 2022-07, with the labels that each got.

#27 增加 f2ccloud 组织
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: release-note-none, lgtm, approved

#28 Add merge_commit_template for tide plugin
  config/prow/config.yaml
Labels: release-note-none, lgtm, approved, kind/improvement

#29 Add halo-sigs organization into prow
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: kind/feature, release-note-none, lgtm, approved
