Repository halo-dev/test-infra, pull requests merged in 2022-04, with the labels that each got.

#12 Change default merge_method for metersphere
  config/prow/config.yaml
Labels: lgtm, approved

#13 Config approve plugin require_self_approval to true
  config/prow/plugins.yaml
Labels: lgtm, approved

#14 Add repos config item for approve plugin
  config/prow/plugins.yaml
Labels: lgtm, approved

#15 Change prow domain name to prow.halo.run
  README.md
  config/prow/cluster/tls-ing_ingress.yaml
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: lgtm, approved

#16 Configure milestone plugin for halo-dev
  config/prow/plugins.yaml
Labels: lgtm, approved

#17 Refine rbac for Prow components
  config/prow/cluster/crier_rbac.yaml
  config/prow/cluster/deck_rbac.yaml
  config/prow/cluster/prow_controller_manager_rbac.yaml
  config/prow/cluster/sinker_rbac.yaml
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: lgtm, approved

#18 Config external plugin: cherrypick
  config/prow/plugins.yaml
Labels: kind/feature, lgtm, approved

#19 Fix invalid configuration on cherrypicker plugin
  config/prow/plugins.yaml
Labels: kind/bug, lgtm, approved
